### PR TITLE
148 Added Admin panel in heartbeat site

### PR DESCRIPTION
**Pull request by cedricabuso**

### CODE REVIEW

**Comment by ravenjohn** [comment]
dont md5 on client.

**Comment by cedricabuso** [comment]
@ravenjohn Noted :)

**Comment by cedricabuso** [comment]
@ravenjohn Oh, I remembered, I md5'ed on the client because I didn't want the pass phrase to be shown on the request to gain access on the admin panel.

**Comment by ravenjohn** [comment]
md5 is not secure

**Comment by cedricabuso** [comment]
@ravenjohn Ok, there's a list of emails who can access it anyway. :)

**Comment by nhvu1988** [comment]
@ravenjohn tested and everything work fine, please merge when you finish checking coding quality :)

**Pull request merged**
