### PR TITLE
224 Revision on file structure. And revision on getting information of us er logged in to avoid exposed google access token.

### PR DESCRIPTION
**Pull request by cedricabuso**
Revised file structure to make it the same with what everyone's doing.

folder_name -> index.html + resources

*Note: I put them in the same pull request since the changes are the same.

### CODE REVIEW

**Comment by nhvu1988** [comment]
@ravenjohn checked, please merge this :)

**Comment by ravenjohn** [comment]
@cedricabuso it's not advisable to change URLs since there are users who doesnt update their extensions. there links will be unavailable once I make this live

**Comment by cedricabuso** [comment]
@ravenjohn Oh, ok, will revert the changes on the file structure then.

**Comment by cedricabuso** [comment]
@ravenjohn Updated :)

**Comment by cedricabuso** [comment]
I think Vu2 hasn't tested this yet, though. :)

**Pull request merged**
